# Generated by Django 5.2.17 on 2026-09-01 22:01

from django.db import migrations


def create_role_groups(apps, schema_editor):
    """Covers #45: Gestor/Operador as the two roles a Membership can
    have within a company - the permission check itself
    (request.user.groups.filter(name='Gestor').exists()) is wired up
    by #29/#47, which actually need it."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Gestor')
    Group.objects.get_or_create(name='Operador')


def remove_role_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Gestor', 'Operador']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_membership'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.RunPython(create_role_groups, remove_role_groups),
    ]
