# Generated by Django 5.2.17 on 2026-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
