# Generated by Django 5.2.17 on 2026-09-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_membership_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_categor_607069_idx',
            old_name='inventory_p_categor_b457a1_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='category_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='inventory.company'),
        ),
        # AlterField trocado por Remove+Add: "category" tinha o mesmo
        # nome antes (texto) e depois (FK), então o Django tentava
        # converter a coluna de texto direto pra número no lugar - e
        # quebra em qualquer produto com categoria de verdade
        # cadastrada (ex.: "Fixação" não é um número). Remover e criar
        # de novo evita essa conversão impossível.
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
    ]
