# Generated by Django 5.2.17 on 2026-09-14 20:21

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Product = apps.get_model('inventory', 'Product')

    for product in Product.objects.all():
        texto = product.category_text.strip()
        if not texto:
            continue  # produto sem categoria continua sem categoria

        categoria, _ = Category.objects.get_or_create(
            company=product.company,
            name__iexact=texto,
            defaults={'name': texto, 'company': product.company},
        )
        product.category = categoria
        product.save(update_fields=['category'])


def reverse_populate_categories(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories),
        migrations.RemoveField(model_name='product', name='category_text'),
    ]
