# Generated by Django 5.2.17 on 2026-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=49.9, max_digits=10),
            preserve_default=False,
        ),
    ]
