# Generated by Django 5.2.17 on 2026-09-14 22:12

from decimal import Decimal

from django.db import migrations


def populate_unit_price(apps, schema_editor):
    StockMovement = apps.get_model('inventory', 'StockMovement')

    for movement in StockMovement.objects.all():
        # Não existe como recuperar o preço real de uma venda passada - o
        # melhor esforço possível é usar o preço atual do produto como
        # aproximação pro histórico. Daqui pra frente (via services.py),
        # o valor gravado vai ser o preço no momento exato da movimentação.
        movement.unit_price = movement.product.price
        movement.save(update_fields=['unit_price'])


def reverse_populate_unit_price(apps, schema_editor):
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockMovement.objects.update(unit_price=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockmovement_is_sale_stockmovement_unit_price'),
    ]

    operations = [
        migrations.RunPython(populate_unit_price, reverse_populate_unit_price),
    ]
