# Generated by Django 5.2.17 on 2026-09-15 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_fix_is_sale_on_legacy_in_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'OUT'), ('is_sale', False), _connector='OR'), name='stockmovement_is_sale_only_on_out'),
        ),
    ]
